const ForthData=[
    {
        id:1,
        src:"trenchcoat.jpg",
        title:"Trenchcoat"
    },
    {
        id:2,
        src:"jeans.jpg",
        title:"Jeans"
    },
    {
        id:3,
        src:"cardigan.jpg",
        title:"Cardigan"
    },
    {
        id:4,
        src:"jacket.jpg",
        title:"Jacket"
    },
    {
        id:5,
        src:"sweater.jpg",
        title:"Sweater"
    },
    {
        id:6,
        src:"lawndress.jpg",
        title:"Lawndress"
    },
    {
        id:7,
        src:"socks.jpg",
        title:"Socks"
    },
    {
        id:8,
        src:"fleece.jpg",
        title:"Fleece"
    },
    {
        id:9,
        src:"wedding.jpg",
        title:"Wedding"
    },
    {
        id:10,
        src:"hoodie.jpg",
        title:"Hoodie"
    },
]
export default ForthData